[theme]
base="light"
primaryColor="#3B82F6"            # Light blue → used for primary buttons
backgroundColor="#ffffff"
secondaryBackgroundColor="#f6f7fb" # used as background for secondary buttons / containers
textColor="#0f172a"

[server]
enableXsrfProtection = true
